language: node_js
sudo: false
node_js:
  - "0.10"
  - "0.12"
  - "iojs"
before_install:
  - "npm install -g gulp"
  - "npm install -g bower"
  - "npm install -g grunt-cli"
before_script:
  - "npm run bower"
script:
  - "npm test"
